// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeNickname(arg1) {
  return window['go']['main']['App']['ChangeNickname'](arg1);
}

export function ChangePassword(arg1, arg2) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2);
}

export function CreateComment(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateComment'](arg1, arg2, arg3);
}

export function CreatePost(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePost'](arg1, arg2, arg3);
}

export function CreateUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2, arg3);
}

export function DeleteCharacter(arg1) {
  return window['go']['main']['App']['DeleteCharacter'](arg1);
}

export function DeleteComment(arg1) {
  return window['go']['main']['App']['DeleteComment'](arg1);
}

export function DeletePost(arg1) {
  return window['go']['main']['App']['DeletePost'](arg1);
}

export function GenerateCharacters(arg1) {
  return window['go']['main']['App']['GenerateCharacters'](arg1);
}

export function GetAllCharacterStats() {
  return window['go']['main']['App']['GetAllCharacterStats']();
}

export function GetAllCharacters() {
  return window['go']['main']['App']['GetAllCharacters']();
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function GetBBSConfig() {
  return window['go']['main']['App']['GetBBSConfig']();
}

export function GetComments(arg1) {
  return window['go']['main']['App']['GetComments'](arg1);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetHobbies() {
  return window['go']['main']['App']['GetHobbies']();
}

export function GetJobCategories() {
  return window['go']['main']['App']['GetJobCategories']();
}

export function GetLLMConfig() {
  return window['go']['main']['App']['GetLLMConfig']();
}

export function GetMBTITypes() {
  return window['go']['main']['App']['GetMBTITypes']();
}

export function GetPinnedPosts() {
  return window['go']['main']['App']['GetPinnedPosts']();
}

export function GetPost(arg1) {
  return window['go']['main']['App']['GetPost'](arg1);
}

export function GetPosts(arg1, arg2) {
  return window['go']['main']['App']['GetPosts'](arg1, arg2);
}

export function GetWebServerConfig() {
  return window['go']['main']['App']['GetWebServerConfig']();
}

export function IsAIActivityRunning() {
  return window['go']['main']['App']['IsAIActivityRunning']();
}

export function IsDatabaseConnected() {
  return window['go']['main']['App']['IsDatabaseConnected']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function IsWebServerRunning() {
  return window['go']['main']['App']['IsWebServerRunning']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RecommendPost(arg1) {
  return window['go']['main']['App']['RecommendPost'](arg1);
}

export function ReconnectDatabase() {
  return window['go']['main']['App']['ReconnectDatabase']();
}

export function ResetDatabase(arg1) {
  return window['go']['main']['App']['ResetDatabase'](arg1);
}

export function SaveBBSConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveBBSConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveLLMConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['SaveLLMConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function SetUserAdmin(arg1, arg2) {
  return window['go']['main']['App']['SetUserAdmin'](arg1, arg2);
}

export function StartAIActivity() {
  return window['go']['main']['App']['StartAIActivity']();
}

export function StartWebServer(arg1, arg2) {
  return window['go']['main']['App']['StartWebServer'](arg1, arg2);
}

export function StopAIActivity() {
  return window['go']['main']['App']['StopAIActivity']();
}

export function StopWebServer() {
  return window['go']['main']['App']['StopWebServer']();
}

export function TestLLMConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestLLMConnection'](arg1, arg2, arg3);
}

export function UpdateCharacter(arg1) {
  return window['go']['main']['App']['UpdateCharacter'](arg1);
}

export function UpdateComment(arg1, arg2) {
  return window['go']['main']['App']['UpdateComment'](arg1, arg2);
}

export function UpdatePost(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdatePost'](arg1, arg2, arg3, arg4);
}
