// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function BatchDeleteCharacters(arg1:Array<number>):Promise<void>;

export function BatchSetCharacterActive(arg1:Array<number>,arg2:boolean):Promise<void>;

export function ChangeNickname(arg1:string):Promise<void>;

export function ChangePassword(arg1:string,arg2:string):Promise<void>;

export function CreateComment(arg1:number,arg2:string,arg3:any):Promise<models.Comment>;

export function CreateNewDatabase(arg1:string):Promise<void>;

export function CreatePost(arg1:string,arg2:string,arg3:boolean):Promise<models.Post>;

export function CreateUser(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteCharacter(arg1:number):Promise<void>;

export function DeleteComment(arg1:number):Promise<void>;

export function DeleteDatabase(arg1:string):Promise<void>;

export function DeletePost(arg1:number):Promise<void>;

export function GenerateCharacters(arg1:number):Promise<Array<models.AICharacter>>;

export function GetAllCharacterStats():Promise<Record<number, main.CharacterStats>>;

export function GetAllCharacters():Promise<Array<models.AICharacter>>;

export function GetAllUsers():Promise<Array<models.User>>;

export function GetAppMode():Promise<string>;

export function GetBBSConfig():Promise<models.BBSConfig>;

export function GetCharacterRefValues():Promise<Record<string, string>>;

export function GetComments(arg1:number):Promise<Array<models.Comment>>;

export function GetCurrentDatabase():Promise<string>;

export function GetCurrentUser():Promise<models.User>;

export function GetDatabaseInfo():Promise<Record<string, any>>;

export function GetDatabaseList():Promise<Array<string>>;

export function GetHobbies():Promise<Array<string>>;

export function GetJobCategories():Promise<Array<string>>;

export function GetLLMConfig():Promise<models.LLMConfig>;

export function GetMBTIDescriptions():Promise<Record<string, string>>;

export function GetMBTITypes():Promise<Array<string>>;

export function GetPinnedPosts():Promise<Array<models.Post>>;

export function GetPost(arg1:number):Promise<models.Post>;

export function GetPosts(arg1:number,arg2:number):Promise<models.PostList>;

export function GetPrompt(arg1:string):Promise<string>;

export function GetWebServerConfig():Promise<Record<string, any>>;

export function IsAIActivityRunning():Promise<boolean>;

export function IsDatabaseConnected():Promise<boolean>;

export function IsLoggedIn():Promise<boolean>;

export function IsWebServerRunning():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<models.User>;

export function OpenCharacterManagerWindow():Promise<void>;

export function OpenLogFile():Promise<void>;

export function RecommendPost(arg1:number):Promise<void>;

export function ReconnectDatabase():Promise<void>;

export function ResetCharacterRefValue(arg1:string):Promise<string>;

export function ResetDatabase(arg1:string):Promise<void>;

export function ResetMBTIDescription(arg1:string):Promise<void>;

export function ResetPrompt(arg1:string):Promise<void>;

export function SaveBBSConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string):Promise<void>;

export function SaveCharacterRefValue(arg1:string,arg2:string):Promise<void>;

export function SaveLLMConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number,arg8:number,arg9:number):Promise<void>;

export function SaveMBTIDescription(arg1:string,arg2:string):Promise<void>;

export function SavePrompt(arg1:string,arg2:string):Promise<void>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;

export function SetUserAdmin(arg1:number,arg2:boolean):Promise<void>;

export function StartAIActivity():Promise<void>;

export function StartWebServer(arg1:string,arg2:boolean,arg3:boolean,arg4:string,arg5:string):Promise<void>;

export function StopAIActivity():Promise<void>;

export function StopWebServer():Promise<void>;

export function SwitchDatabase(arg1:string):Promise<void>;

export function TestLLMConnection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateCharacter(arg1:models.AICharacter):Promise<void>;

export function UpdateComment(arg1:number,arg2:string):Promise<void>;

export function UpdatePost(arg1:number,arg2:string,arg3:string,arg4:boolean):Promise<void>;
