// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchDeleteCharacters(arg1) {
  return window['go']['main']['App']['BatchDeleteCharacters'](arg1);
}

export function BatchSetCharacterActive(arg1, arg2) {
  return window['go']['main']['App']['BatchSetCharacterActive'](arg1, arg2);
}

export function ChangeNickname(arg1) {
  return window['go']['main']['App']['ChangeNickname'](arg1);
}

export function ChangePassword(arg1, arg2) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2);
}

export function CreateComment(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateComment'](arg1, arg2, arg3);
}

export function CreateNewDatabase(arg1) {
  return window['go']['main']['App']['CreateNewDatabase'](arg1);
}

export function CreatePost(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePost'](arg1, arg2, arg3);
}

export function CreateUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2, arg3);
}

export function DeleteCharacter(arg1) {
  return window['go']['main']['App']['DeleteCharacter'](arg1);
}

export function DeleteComment(arg1) {
  return window['go']['main']['App']['DeleteComment'](arg1);
}

export function DeleteDatabase(arg1) {
  return window['go']['main']['App']['DeleteDatabase'](arg1);
}

export function DeletePost(arg1) {
  return window['go']['main']['App']['DeletePost'](arg1);
}

export function ExportPromptSettings() {
  return window['go']['main']['App']['ExportPromptSettings']();
}

export function ExportReferenceValues() {
  return window['go']['main']['App']['ExportReferenceValues']();
}

export function GenerateCharacters(arg1) {
  return window['go']['main']['App']['GenerateCharacters'](arg1);
}

export function GetAllCharacterStats() {
  return window['go']['main']['App']['GetAllCharacterStats']();
}

export function GetAllCharacters() {
  return window['go']['main']['App']['GetAllCharacters']();
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function GetAppMode() {
  return window['go']['main']['App']['GetAppMode']();
}

export function GetAvatarList(arg1) {
  return window['go']['main']['App']['GetAvatarList'](arg1);
}

export function GetBBSConfig() {
  return window['go']['main']['App']['GetBBSConfig']();
}

export function GetCharacterRefValues() {
  return window['go']['main']['App']['GetCharacterRefValues']();
}

export function GetComments(arg1) {
  return window['go']['main']['App']['GetComments'](arg1);
}

export function GetCurrentDatabase() {
  return window['go']['main']['App']['GetCurrentDatabase']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDatabaseInfo() {
  return window['go']['main']['App']['GetDatabaseInfo']();
}

export function GetDatabaseList() {
  return window['go']['main']['App']['GetDatabaseList']();
}

export function GetGenSettings() {
  return window['go']['main']['App']['GetGenSettings']();
}

export function GetHobbies() {
  return window['go']['main']['App']['GetHobbies']();
}

export function GetJobCategories() {
  return window['go']['main']['App']['GetJobCategories']();
}

export function GetLLMConfig() {
  return window['go']['main']['App']['GetLLMConfig']();
}

export function GetMBTIDescriptions() {
  return window['go']['main']['App']['GetMBTIDescriptions']();
}

export function GetMBTITypes() {
  return window['go']['main']['App']['GetMBTITypes']();
}

export function GetPinnedPosts() {
  return window['go']['main']['App']['GetPinnedPosts']();
}

export function GetPost(arg1) {
  return window['go']['main']['App']['GetPost'](arg1);
}

export function GetPosts(arg1, arg2) {
  return window['go']['main']['App']['GetPosts'](arg1, arg2);
}

export function GetPrompt(arg1) {
  return window['go']['main']['App']['GetPrompt'](arg1);
}

export function GetWebServerConfig() {
  return window['go']['main']['App']['GetWebServerConfig']();
}

export function ImportPromptSettings() {
  return window['go']['main']['App']['ImportPromptSettings']();
}

export function ImportReferenceValues() {
  return window['go']['main']['App']['ImportReferenceValues']();
}

export function IsAIActivityRunning() {
  return window['go']['main']['App']['IsAIActivityRunning']();
}

export function IsDatabaseConnected() {
  return window['go']['main']['App']['IsDatabaseConnected']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function IsWebServerRunning() {
  return window['go']['main']['App']['IsWebServerRunning']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function OpenCharacterManagerWindow() {
  return window['go']['main']['App']['OpenCharacterManagerWindow']();
}

export function OpenLogFile() {
  return window['go']['main']['App']['OpenLogFile']();
}

export function RecommendPost(arg1) {
  return window['go']['main']['App']['RecommendPost'](arg1);
}

export function ReconnectDatabase() {
  return window['go']['main']['App']['ReconnectDatabase']();
}

export function ResetCharacterRefValue(arg1) {
  return window['go']['main']['App']['ResetCharacterRefValue'](arg1);
}

export function ResetDatabase(arg1) {
  return window['go']['main']['App']['ResetDatabase'](arg1);
}

export function ResetMBTIDescription(arg1) {
  return window['go']['main']['App']['ResetMBTIDescription'](arg1);
}

export function ResetPrompt(arg1) {
  return window['go']['main']['App']['ResetPrompt'](arg1);
}

export function SaveBBSConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveBBSConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveCharacterRefValue(arg1, arg2) {
  return window['go']['main']['App']['SaveCharacterRefValue'](arg1, arg2);
}

export function SaveGenSettings(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveGenSettings'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveLLMConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['SaveLLMConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function SaveMBTIDescription(arg1, arg2) {
  return window['go']['main']['App']['SaveMBTIDescription'](arg1, arg2);
}

export function SavePrompt(arg1, arg2) {
  return window['go']['main']['App']['SavePrompt'](arg1, arg2);
}

export function SaveWebServerConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveWebServerConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SelectFile(arg1, arg2) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2);
}

export function SetUserAdmin(arg1, arg2) {
  return window['go']['main']['App']['SetUserAdmin'](arg1, arg2);
}

export function StartAIActivity() {
  return window['go']['main']['App']['StartAIActivity']();
}

export function StartWebServer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartWebServer'](arg1, arg2, arg3, arg4, arg5);
}

export function StopAIActivity() {
  return window['go']['main']['App']['StopAIActivity']();
}

export function StopWebServer() {
  return window['go']['main']['App']['StopWebServer']();
}

export function SwitchDatabase(arg1) {
  return window['go']['main']['App']['SwitchDatabase'](arg1);
}

export function TestLLMConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestLLMConnection'](arg1, arg2, arg3);
}

export function UpdateCharacter(arg1) {
  return window['go']['main']['App']['UpdateCharacter'](arg1);
}

export function UpdateComment(arg1, arg2) {
  return window['go']['main']['App']['UpdateComment'](arg1, arg2);
}

export function UpdatePost(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdatePost'](arg1, arg2, arg3, arg4);
}
